<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-3Q10494" name="Tests.CucumberRunner" tests="2" failures="1" timestamp="2024-09-15T23:26:23 IST" time="55.659" errors="0">
  <testcase name="runScenario" time="24.029" classname="Tests.CucumberRunner"/>
  <system-out/>
  <testcase name="runScenario" time="31.630" classname="Tests.CucumberRunner">
    <failure type="java.lang.AssertionError" message="expected [FAIL] but found [PASS]">
      <![CDATA[java.lang.AssertionError: expected [FAIL] but found [PASS]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at StepDefinations.LoginTest.verify_user_is_able_to_successfully_login(LoginTest.java:74)
at âœ½.Login status should be "FAIL"(file:///E:/sandip/work/Framework1/src/test/java/Features/feature.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Tests.CucumberRunner -->
